= Kotlin-SpringBoot-GraphQL-Mongo POC
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Overview ==
This is a spike to help determine the technology stack to use. Initially, this is:

* SpringBoot
* Kotlin
* GraphQL
* MongoDB
* KMongo

== Getting Started
. Start Mongod: `mongod --config /usr/local/etc/mongod.conf`
+
.mongod.conf
[source,bash]
----
systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /usr/local/var/mongodb
net:
  bindIp: 127.0.0.1
----
. Create a Mongo db. Type the following in the mongo shell: `use pricing`
. Type the following in the mongo shell: `db.dayAheadMarket.insertOne( {hourEnding: NumberInt(2), zone: "HB_SOUTH", price: 18.79 } );`
+
By default, the mongo shell treats all numbers as floating-point values. So we need to explicitly specify what type of number we want to use e.g. NumberInt or NumberLong. See http://docs.mongodb.org/manual/core/shell-types/.
. Run `gradle bootRun`
. Open a browser to http://localhost:8080/graphiql
. Run some queries. For example:

.Simple 'Version' Query
[source,bash]
----
query {
  version
}
----

.Prices By Zone Query
[source,bash]
----
query {
  pricesByZone(zone: "HB_HOUSTON") {
    hourEnding
    price
  }
}
----

.Price Mutation
[source,bash]
----
mutation {
  dayAheadMarketCreate(input: {hourEnding: 1, zone: "HB_SOUTH", price: 18.79 }) {
    id
    hourEnding
    zone
    price
  }
}
----

== Evaluation

== References
* https://medium.com/@aronbalog/spring-boot-kotlin-graphql-mongo-e73f25df6ab9
* https://litote.org/kmongo/quick-start/
* https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html


== TODOs
. Incorporate KMongo
. Use BigDecimal for prices
. Eliminate \_class field from insert (injected by Spring?)
. Change query to make it clear it is retrieving Day Ahead Market (DAM) pricies, i. e. `pricesByZone` should be something like `damPricesByZone`
